### ISSUE TITLE
Add benchmark for find() algorithm

### ISSUE THREAD

**Issue by kylelutz** [kylelutz/compute#325]
Add a benchmark for the [`find()`](http://kylelutz.github.io/compute/boost/compute/find.html) algorithm (i.e. `perf_find`).

See the [`perf/perf_count.cpp`](https://github.com/kylelutz/compute/blob/master/perf/perf_count.cpp) benchmark for an example/template.

It would also be good to add a corresponding benchmark for the STL `std::find()` algorithm (i.e. `perf_stl_find`).

**Comment by haahh** [comment]
I may be closed. See https://github.com/kylelutz/compute/pull/444.

**Comment by kylelutz** [comment]
Closed. Thanks!
