### ISSUE TITLE
buffer::clone returns buffer object created with default mem flags

### ISSUE THREAD

**Issue by j8asic** [kylelutz/compute#414]
Shouldn't maybe buffer::clone respect and use same cl_mem_flags as buffer being cloned from?

**Comment by kylelutz** [comment]
That makes sense to me, I was probably just lazy when writing that function. Would you be interested in implementing this change?

**Comment by kylelutz** [comment]
Implemented in PR #423.

**Comment by j8asic** [comment]
Thanks for the patch. Sorry, wasn't active on the project last month, else I would have written those few lines.

**Comment by kylelutz** [comment]
No problem. Thanks for the bug report!
